server:
  port: 9000

  # Cookies are per-domain, multiple apps running on localhost on different ports share cookies.
  # This can create conflicts. We ensure the session cookie is different from the cookie that
  # the client application uses.
  servlet:
    session:
      cookie:
        name: MCP_AUTHSERVER_SESSION

spring:
  security:
    # Provide a default "user"
    user:
      name: user
      password: password

    # Configure the Authorization Server
    oauth2:
      authorizationserver:
        client:
          oidc-client:
            registration:
              client-id: "mcp-client"
              client-secret: "{noop}mcp-secret"
              client-authentication-methods:
                - "client_secret_basic"
              authorization-grant-types:
                - "authorization_code"
                - "client_credentials"
                - "refresh_token"
              scopes:
                - "openid"
                - "profile"
                - "email"
              redirect-uris:
                # The client application can technically run on any port
                #- "http://127.0.0.1:8080/authorize/oauth2/code/authserver"
                #- "http://localhost:8080/authorize/oauth2/code/authserver"
                #- "http://localhost:8081/authorize/oauth2/code/authserver"
                #- "http://localhost:8082/authorize/oauth2/code/authserver"
                - "http://localhost:8080/login/oauth2/code/authcode"
logging:
  level:
    org:
      springframework:
        security: TRACE
